### ISSUE TITLE
1.18.2 update would be nice :)

### ISSUE THREAD

**Issue by mvilk** [TehBrian/BuildersUtilities#39]
Everything else seems to be working in 1.18.2, but /bu rc command throws this error and is not working.
I'm using purpur server which is fork of paper.
```
[16:48:33 INFO]: Munaville issued server command: /bu rc
[16:48:33 ERROR]: [BuildersUtilities] Exception executing command handler
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R1/entity/CraftPlayer
        at xyz.tehbrian.buildersutilities.command.BuildersUtilitiesCommand.lambda$register$1(BuildersUtilitiesCommand.java:84) ~[buildersutilities-1.4.0 (2).jar:?]
        at xyz.tehbrian.buildersutilities.libs.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:58) ~[buildersutilities-1.4.0 (2).jar:?]
        at xyz.tehbrian.buildersutilities.libs.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:120) ~[buildersutilities-1.4.0 (2).jar:?]
        at xyz.tehbrian.buildersutilities.libs.cloud.CommandManager.executeCommand(CommandManager.java:177) ~[buildersutilities-1.4.0 (2).jar:?]
        at xyz.tehbrian.buildersutilities.libs.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:110) ~[buildersutilities-1.4.0 (2).jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2389) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2200) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2181) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1403) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1396) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1374) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1256) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1625]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer
        ... 26 more
```

**Comment by TehBrian** [comment]
That issue will be fixed once the update for 1.18.2 comes out, which should be soon! :) Keep an eye out.
